version: '2'
services:
  saha-app:
    image: saha
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://saha-mysql:3306/saha?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  saha-front:
    image: saha-front
    ports:
      - 9000:9000
  saha-mysql:
    extends:
      file: mysql.yml
      service: saha-mysql
volumes:
  my-datavolume:      
